import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import crypto from 'node:crypto';
import AdmZip from 'adm-zip';
import {listContent,toggleContent,optionList,shaderProperties,replacePackSelection} from '../electron/contentConfig.js';
import {checkContent,getContentPlans,applyContentUpdate} from '../electron/contentManager.js';
const rootFor=async t=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'novex-content-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));for(const folder of ['mods','resourcepacks','shaderpacks','config'])await fs.mkdir(path.join(root,folder));return root;};
async function mod(root,name,id){const zip=new AdmZip();zip.addFile('fabric.mod.json',Buffer.from(JSON.stringify({id,version:'1'})));await fs.writeFile(path.join(root,'mods',name),zip.toBuffer());}
test('resource packs toggle without moving files or changing other options and restore priority',async t=>{const root=await rootFor(t);for(const name of ['a.zip','b.zip','c.zip'])await fs.writeFile(path.join(root,'resourcepacks',name),'pack');const original='renderDistance:12\r\nresourcePacks:["vanilla","file/a.zip","file/b.zip","file/c.zip"]\r\nsoundCategory_master:0.5\r\n';await fs.writeFile(path.join(root,'options.txt'),original);await toggleContent(root,'resourcepack','b.zip',false);let text=await fs.readFile(path.join(root,'options.txt'),'utf8');assert.deepEqual(optionList(text),['vanilla','file/a.zip','file/c.zip']);assert.match(text,/renderDistance:12\r\n/);assert.equal(await fs.readFile(path.join(root,'resourcepacks/b.zip'),'utf8'),'pack');await toggleContent(root,'resourcepack','b.zip',true);assert.equal(await fs.readFile(path.join(root,'options.txt'),'utf8'),original);await replacePackSelection(root,'resourcepack','b.zip','new.zip');assert.deepEqual(optionList(await fs.readFile(path.join(root,'options.txt'),'utf8')),['vanilla','file/a.zip','file/new.zip','file/c.zip']);});
test('Iris toggles one shader, handles escaped filenames, preserves unrelated properties and refuses unsupported instances',async t=>{const root=await rootFor(t);for(const name of ['One Pack.zip','Two.zip'])await fs.writeFile(path.join(root,'shaderpacks',name),'pack');assert.equal((await listContent(root,'shader')).supported,false);await assert.rejects(toggleContent(root,'shader','One Pack.zip',true),/Iris/);await mod(root,'renamed.jar','iris');await fs.writeFile(path.join(root,'config/iris.properties'),'# original\nmaxShadowRenderDistance=24\n');await toggleContent(root,'shader','One Pack.zip',true);assert.equal(shaderProperties(await fs.readFile(path.join(root,'config/iris.properties'),'utf8')).shaderPack,'One Pack.zip');await toggleContent(root,'shader','Two.zip',true);const list=await listContent(root,'shader');assert.deepEqual(list.items.filter(i=>i.enabled).map(i=>i.name),['Two.zip']);await toggleContent(root,'shader','Two.zip',false);assert.equal((await listContent(root,'shader')).items.some(i=>i.enabled),false);assert.match(await fs.readFile(path.join(root,'config/iris.properties'),'utf8'),/maxShadowRenderDistance=24/);});
test('enabling a duplicate mod ID is blocked and disabling retains original bytes',async t=>{const root=await rootFor(t);await mod(root,'a.jar','same');await mod(root,'b.jar.disabled','same');await assert.rejects(toggleContent(root,'mod','b.jar.disabled',true),/Another enabled/);const bytes=await fs.readFile(path.join(root,'mods/a.jar'));await toggleContent(root,'mod','a.jar',false);await toggleContent(root,'mod','b.jar.disabled',true);assert.deepEqual(await fs.readFile(path.join(root,'mods/a.jar.disabled')),bytes);await assert.rejects(toggleContent(root,'mod','../a.jar',true));});
const sha=data=>crypto.createHash('sha1').update(data).digest('hex');
test('pack updates verify before replacing, preserve order, and reject incompatible or changed files',async t=>{const root=await rootFor(t),original=global.fetch;t.after(()=>global.fetch=original);await fs.writeFile(path.join(root,'resourcepacks/old.zip'),'old');await fs.writeFile(path.join(root,'options.txt'),'resourcePacks:["vanilla","file/old.zip","file/other.zip"]\n');const old={id:'old',project_id:'project',version_number:'1',game_versions:['1.21.11'],loaders:['minecraft'],date_published:'2025-01-01'},latest={...old,id:'new',version_number:'2',version_type:'release',date_published:'2026-01-01',files:[{filename:'new.zip',url:'https://cdn.modrinth.com/new.zip',size:3,hashes:{sha1:sha('new')}}]};let wrong=false,fail=false;
global.fetch=async(url)=>{url=String(url);if(url.includes('version_files'))return new Response(JSON.stringify({[sha('old')]:old}));if(url.includes('/version/new'))return new Response(JSON.stringify({...latest,game_versions:wrong?['1.20.1']:latest.game_versions}));if(url.includes('/project/project/version'))return new Response(JSON.stringify([latest]));if(url.includes('/project/project'))return new Response(JSON.stringify({title:'Pack',project_type:'resourcepack'}));return new Response(fail?'bad':'new');};
const instance={minecraftVersion:'1.21.11',loader:'fabric'};const result=await checkContent(root,'resourcepack',instance);const plan=getContentPlans(root,'resourcepack',[result.items[0].updateId])[0];wrong=true;await assert.rejects(applyContentUpdate(plan),/does not support/);wrong=false;fail=true;await assert.rejects(applyContentUpdate(plan),/integrity/);assert.equal(await fs.readFile(path.join(root,'resourcepacks/old.zip'),'utf8'),'old');fail=false;await applyContentUpdate(plan);assert.equal(await fs.readFile(path.join(root,'resourcepacks/new.zip'),'utf8'),'new');assert.deepEqual(optionList(await fs.readFile(path.join(root,'options.txt'),'utf8')),['vanilla','file/new.zip','file/other.zip']);await assert.rejects(fs.stat(path.join(root,'resourcepacks/old.zip')));});
test('bulk resource-pack toggles retain priority even when re-enabled in reverse selection order',async t=>{const root=await rootFor(t);for(const name of ['a.zip','b.zip','c.zip'])await fs.writeFile(path.join(root,'resourcepacks',name),'pack');await fs.writeFile(path.join(root,'options.txt'),'resourcePacks:["vanilla","file/a.zip","file/b.zip","file/c.zip"]\n');await toggleContent(root,'resourcepack','a.zip',false);await toggleContent(root,'resourcepack','b.zip',false);await toggleContent(root,'resourcepack','b.zip',true);await toggleContent(root,'resourcepack','a.zip',true);assert.deepEqual(optionList(await fs.readFile(path.join(root,'options.txt'),'utf8')),['vanilla','file/a.zip','file/b.zip','file/c.zip']);});
