import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import AdmZip from 'adm-zip';
import {resolveInside,safeSegment} from './pathSafety.js';
import {listInstalledMods,setModEnabled} from './fileManager.js';
export const contentFolders={mod:'mods',resourcepack:'resourcepacks',shader:'shaderpacks'};
export function contentPath(root,kind,name){if(!Object.hasOwn(contentFolders,kind))throw new Error('Invalid content type.');safeSegment(name);return resolveInside(root,`${contentFolders[kind]}/${name}`);}
async function read(root,name){const file=resolveInside(root,name);try{if((await fs.stat(file)).size>2*1024*1024)throw new Error('Configuration is too large.');return await fs.readFile(file,'utf8');}catch(e){if(e.code==='ENOENT')return '';throw e;}}
export async function atomicConfig(root,name,text){const target=resolveInside(root,name),temporary=resolveInside(root,`${name}.${crypto.randomUUID()}.tmp`);await fs.mkdir(path.dirname(target),{recursive:true});try{await fs.writeFile(temporary,text,{flag:'wx'});await fs.rename(temporary,target);}finally{await fs.rm(temporary,{force:true});}}
export function optionList(text,key='resourcePacks'){
    const line=text.split(/\r?\n/).find(line=>line.startsWith(key+':'));if(!line)return [];
    const value=JSON.parse(line.slice(key.length+1));if(!Array.isArray(value)||value.some(item=>typeof item!=='string'))throw new Error('Minecraft resource-pack settings are invalid. Fix options.txt before changing packs.');return value;
}
export function replaceOption(text,key,value){const newline=text.includes('\r\n')?'\r\n':'\n',lines=text.split(/\r?\n/);let found=false;const result=lines.filter(line=>{if(!line.startsWith(key+':'))return true;if(found)return false;found=true;return true;}).map(line=>line.startsWith(key+':')?`${key}:${JSON.stringify(value)}`:line);if(!found)result.splice(result.length-(result.at(-1)===''?1:0),0,`${key}:${JSON.stringify(value)}`);return result.join(newline);}
export function shaderProperties(text){const result={};for(const line of text.split(/\r?\n/)){const match=line.match(/^\s*(shaderPack|enableShaders)\s*[=:]\s*(.*)$/);if(match){if(/(?<!\\)(?:\\\\)*\\$/.test(match[2]))throw new Error('Multiline shader configuration must be edited in Iris.');result[match[1]]=match[2].replace(/\\u([0-9a-f]{4})|\\(.)/gi,(_all,hex,char)=>hex?String.fromCharCode(parseInt(hex,16)):({t:'\t',r:'\r',n:'\n',f:'\f'}[char]||char));}}return result;}
function setShaderProperty(text,key,value){const encoded=String(value).replace(/[\\:=#!\s\u0080-\uffff]/g,char=>'\\u'+char.charCodeAt(0).toString(16).padStart(4,'0'));const lines=text.split(/\r?\n/).filter(line=>!new RegExp(`^\\s*${key}\\s*[=:]`).test(line));if(lines.at(-1)==='')lines.pop();return [...lines,`${key}=${encoded}`,''].join(text.includes('\r\n')?'\r\n':'\n');}
export async function localModIds(root,name){const file=contentPath(root,'mod',name);if((await fs.stat(file)).size>128*1024**2)return [];try{const zip=new AdmZip(file),ids=[];for(const key of ['fabric.mod.json','quilt.mod.json']){const entry=zip.getEntry(key);if(entry&&entry.header.size<1024*1024){const data=JSON.parse(entry.getData().toString());if(data.id)ids.push(data.id);if(data.quilt_loader?.id)ids.push(data.quilt_loader.id);}}
for(const key of ['META-INF/mods.toml','META-INF/neoforge.mods.toml']){const entry=zip.getEntry(key);if(entry&&entry.header.size<1024*1024)for(const match of entry.getData().toString().matchAll(/^\s*modId\s*=\s*["']([^"']+)["']/gm))ids.push(match[1]);}return [...new Set(ids)];}catch{return [];}}
export async function shaderSupport(root){for(const mod of await listInstalledMods(root))if(mod.enabled&&(await localModIds(root,mod.name)).includes('iris'))return true;return false;}
export async function listContent(root,kind){if(kind==='mod')return {items:await listInstalledMods(root),supported:true};const folder=contentFolders[kind];if(!folder)throw new Error('Invalid content type.');const options=kind==='resourcepack'?optionList(await read(root,'options.txt')):[];const config=kind==='shader'?shaderProperties(await read(root,'config/iris.properties')):{};const supported=kind!=='shader'||await shaderSupport(root);const items=[];
for(const entry of await fs.readdir(resolveInside(root,folder),{withFileTypes:true}).catch(e=>{if(e.code==='ENOENT')return [];throw e;})){if(entry.isSymbolicLink()||(!entry.isDirectory()&&!entry.name.toLowerCase().endsWith('.zip')))continue;contentPath(root,kind,entry.name);items.push({name:entry.name,directory:entry.isDirectory(),enabled:kind==='resourcepack'?options.includes('file/'+entry.name):supported&&config.enableShaders!=='false'&&config.shaderPack===entry.name});}return {items,supported};}
export async function toggleContent(root,kind,name,enabled){if(typeof enabled!=='boolean')throw new Error('Invalid enabled state.');const list=await listContent(root,kind);if(!list.items.some(item=>item.name===name))throw new Error('Content file is no longer installed.');
if(kind==='mod'){if(enabled){const ids=await localModIds(root,name);for(const other of list.items.filter(item=>item.enabled&&item.name!==name)){const otherIds=await localModIds(root,other.name);if(ids.some(id=>otherIds.includes(id)))throw new Error(`Another enabled version of this mod exists: ${other.name}. Disable it first.`);}}return setModEnabled(root,name,enabled);}
if(kind==='shader'){if(!list.supported)throw new Error('Enable/install Iris before selecting shaders. Other shader loaders must be configured in-game.');let text=await read(root,'config/iris.properties');const config=shaderProperties(text);if(enabled){text=setShaderProperty(text,'shaderPack',name);text=setShaderProperty(text,'enableShaders',true);}else if(config.shaderPack===name)text=setShaderProperty(text,'enableShaders',false);await atomicConfig(root,'config/iris.properties',text);return;}
const text=await read(root,'options.txt'),packs=optionList(text),id='file/'+name;let positions={};try{positions=JSON.parse(await read(root,'.novex-pack-order.json')||'{}');}catch{throw new Error('Saved pack order is unreadable.');}const index=packs.indexOf(id);if(enabled&&index===-1){const saved=positions[id];let at=packs.length;if(Number.isInteger(saved))at=Math.min(packs.length,Math.max(0,saved));else if(saved&&Array.isArray(saved.before)&&Array.isArray(saved.after)){const after=saved.after.find(value=>packs.includes(value));const before=[...saved.before].reverse().find(value=>packs.includes(value));at=after?packs.indexOf(after):before?packs.indexOf(before)+1:packs.length;}packs.splice(at,0,id);}else if(!enabled&&index!==-1){positions[id]={before:packs.slice(0,index),after:packs.slice(index+1)};packs.splice(index,1);}await atomicConfig(root,'.novex-pack-order.json',JSON.stringify(positions));await atomicConfig(root,'options.txt',replaceOption(text,'resourcePacks',packs));}
export async function replacePackSelection(root,kind,oldName,newName){if(kind==='resourcepack'){const text=await read(root,'options.txt');const packs=optionList(text).map(value=>value==='file/'+oldName?'file/'+newName:value);const positions=JSON.parse(await read(root,'.novex-pack-order.json')||'{}');const oldId='file/'+oldName,newId='file/'+newName;if(Object.hasOwn(positions,oldId)){positions[newId]=positions[oldId];delete positions[oldId];}for(const position of Object.values(positions))if(position&&typeof position==='object')for(const side of ['before','after'])if(Array.isArray(position[side]))position[side]=position[side].map(value=>value===oldId?newId:value);await atomicConfig(root,'.novex-pack-order.json',JSON.stringify(positions));await atomicConfig(root,'options.txt',replaceOption(text,'resourcePacks',packs));}else if(kind==='shader'){const text=await read(root,'config/iris.properties');if(shaderProperties(text).shaderPack===oldName)await atomicConfig(root,'config/iris.properties',setShaderProperty(text,'shaderPack',newName));}}
