import {useEffect,useRef,useState} from 'react';
import type {MinecraftAccount} from '../services/minecraftAccounts';
import type {Appearance,SkinDraft,SkinModel} from '../services/appearance';
import {uiError} from '../services/uiError';
import {useDialogs} from '../components/Dialogs';
import AppearancePreview from '../components/AppearancePreview';
import './Appearance.css';
type Choice={id:string;name:string;image:string;model:SkinModel;draft?:SkinDraft};
export default function AppearancePage({kind,onManage}:{kind:'skins'|'capes';onManage:()=>void}){
    const [account,setAccount]=useState<MinecraftAccount|null>(null),[data,setData]=useState<Appearance|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[choice,setChoice]=useState<Choice|null>(null),[model,setModel]=useState<SkinModel>('classic'),[capeId,setCapeId]=useState(''),[back,setBack]=useState(false);
    const epoch=useRef(0),{confirm}=useDialogs();
    function accept(value:Appearance){setData(value);const active=value.skins.find(s=>s.active);setChoice(active?{...active,image:active.url}:null);setModel(active?.model||'classic');setCapeId(value.capes.find(c=>c.active)?.id||'');}
    useEffect(()=>{
        const reload=async(event?:Event)=>{
            if((event as CustomEvent|undefined)?.detail?.appearance)return;
            const request=++epoch.current;setData(null);setAccount(null);setChoice(null);setCapeId('');setError('');setMessage('');setBusy(true);
            try{const state=await window.novex.minecraftAccounts.list();if(request!==epoch.current)return;const current=state.accounts.find(a=>a.id===state.selectedId)||null;setAccount(current);if(current?.type==='microsoft'){const next=await window.novex.appearance.get(current.id,true);if(request===epoch.current&&next.accountId===current.id)accept(next);}}
            catch(e){if(request===epoch.current)setError(uiError(e,'Unable to load Minecraft appearance. Try Refresh.'));}
            finally{if(request===epoch.current)setBusy(false);}
        };
        void reload();window.addEventListener('novex-minecraft-accounts',reload);return()=>{++epoch.current;window.removeEventListener('novex-minecraft-accounts',reload);};
    },[]);
    async function run(task:(id:string)=>Promise<Appearance>,success:string){
        if(!account||busy)return;const request=epoch.current,id=account.id;setBusy(true);setError('');setMessage('');
        try{const next=await task(id);if(request!==epoch.current||next.accountId!==id)return;accept(next);setMessage(next.warning||success);window.dispatchEvent(new CustomEvent('novex-minecraft-accounts',{detail:{appearance:true}}));}
        catch(e){if(request===epoch.current)setError(uiError(e,'Unable to change Minecraft appearance. Try Refresh before retrying.'));}
        finally{if(request===epoch.current)setBusy(false);}
    }
    async function choose(){if(!account||busy)return;const request=epoch.current;setBusy(true);setError('');setMessage('');try{const draft=await window.novex.appearance.choose(account.id);if(draft&&request===epoch.current){setChoice({id:draft.draftId,name:draft.name,image:draft.image,model:'classic',draft});setModel('classic');}}catch(e){if(request===epoch.current)setError(uiError(e,'Unable to open that skin PNG.'));}finally{if(request===epoch.current)setBusy(false);}}
    const skin=data?.skins.find(s=>s.active),activeCape=data?.capes.find(c=>c.active),selectedCape=data?.capes.find(c=>c.id===capeId);
    const selected=(next:Choice)=>{setChoice(next);setModel(next.model);setMessage('');};
    return <section className="page appearance-page"><header className="appearance-heading"><div><h1>{kind==='skins'?'Skins':'Capes'}</h1><p>{account?`${account.username} · ${account.type==='microsoft'?'Minecraft Java account':'Offline / Local Account'}`:'Select your Minecraft account'}</p></div><button disabled={busy||account?.type!=='microsoft'} onClick={()=>void run(id=>window.novex.appearance.get(id,true),'Profile refreshed.')}>{busy?'Working…':'Refresh'}</button></header>
    {error&&<p role="alert" className="utility-error">{error}</p>}{message&&<p role="status" className="appearance-notice">{message}</p>}
    {account?.type!=='microsoft'?<div className="card empty-state"><p>{busy?'Loading Minecraft account…':'Select a Microsoft account that owns Minecraft Java to manage skins and capes. Offline accounts cannot change Mojang appearance.'}</p><button onClick={onManage}>Manage Minecraft Accounts</button></div>:!data?<div className="card empty-state"><p>{busy?'Loading Minecraft appearance…':'Appearance could not be loaded. Refresh to retry, or refresh your Minecraft account in Settings.'}</p><button disabled={busy} onClick={onManage}>Manage Minecraft Account</button></div>:kind==='skins'?<>
    <div className="appearance-workspace"><section className="card appearance-current"><h2>Current skin</h2><AppearancePreview image={skin?.url} model={skin?.model} back={back}/><strong>{skin?.name||'Default Minecraft skin'}</strong>{skin&&<p>{skin.model==='slim'?'Slim / Alex':'Classic / Steve'} <span className="provider-badge">Active</span></p>}<button className="secondary-button" onClick={()=>setBack(value=>!value)}>{back?'Show Front':'Show Back'}</button><button className="secondary-button" disabled={busy||!skin} onClick={async()=>{if(await confirm('Remove the custom active skin and use Minecraft’s default skin? Saved Novex skins are kept.','Reset Minecraft skin',false))void run(id=>window.novex.appearance.resetSkin(id),'Active skin reset to Minecraft default.');}}>Reset Active Skin</button></section>
    <section className="card appearance-editor"><h2>Choose a skin</h2><p>PNG, 64×64 or legacy 64×32; up to 1 MiB. Selecting a preview does not change your account.</p><button className="secondary-button" disabled={busy} onClick={()=>void choose()}>Upload Skin · Choose PNG</button><div className="appearance-selection"><AppearancePreview image={choice?.image} model={model} back={back} label="Selected skin preview"/><div><strong>{choice?.name||'Choose a PNG or saved skin'}</strong><fieldset disabled={busy||!choice}><legend>Skin model</legend><label><input type="radio" name="skin-model" checked={model==='classic'} onChange={()=>setModel('classic')}/> Classic / Steve</label><label><input type="radio" name="skin-model" checked={model==='slim'} disabled={choice?.draft?.height===32} onChange={()=>setModel('slim')}/> Slim / Alex</label></fieldset><button className="primary-button" disabled={busy||!choice} onClick={()=>{if(choice)void run(id=>choice.draft?window.novex.appearance.upload(id,choice.draft.draftId,model):window.novex.appearance.setSkin(id,choice.id,model),'Skin applied to Minecraft.');}}>{busy?'Working…':'Apply / Use Skin'}</button></div></div><p className="utility-muted">Changes apply to your Minecraft profile. A game already running may need a reconnect or restart to refresh its texture.</p></section></div>
    <h2>Saved in Novex</h2><p className="utility-muted">Uploaded skins are saved on this computer for this account. Minecraft does not provide a cloud skin-history library. Deleting a saved copy does not change your active skin.</p>
    {!data.saved.length&&<p className="empty-state">No saved skins yet. Choose and apply a PNG to save it here.</p>}
    <div className="appearance-grid">{data.saved.map(saved=><article className={`card appearance-item ${choice?.id===saved.id?'selected':''}`} key={saved.id}><button className="appearance-pick" disabled={busy} onClick={()=>selected(saved)} aria-label={`Preview ${saved.name}`}><AppearancePreview image={saved.image} model={saved.model}/><strong>{saved.name}</strong><small>{saved.model==='slim'?'Slim':'Classic'}</small></button><button className="danger-button" disabled={busy} onClick={async()=>{if(await confirm(`Delete “${saved.name}” from this account’s local Novex library? The active Minecraft skin will not be removed.`,'Delete saved skin'))void run(id=>window.novex.appearance.deleteSaved(id,saved.id),'Saved skin deleted from Novex.');}}>Delete Saved Copy</button></article>)}</div>
    {data.skins.some(s=>!s.active)&&<><h2>Other skins returned by Minecraft</h2><div className="appearance-grid">{data.skins.filter(s=>!s.active).map(s=><button className="card appearance-pick" key={s.id} disabled={busy} onClick={()=>selected({...s,image:s.url})}><AppearancePreview image={s.url} model={s.model}/>{s.name}</button>)}</div></>}
    </>:<><section className="card appearance-cape-controls"><div><h2>{activeCape?`Active: ${activeCape.name}`:'No active cape'}</h2><p>Only capes returned by your Minecraft account are shown. Selecting a cape previews it; Apply changes your account.</p></div><button className="primary-button" disabled={busy||!selectedCape||selectedCape.active} onClick={()=>void run(id=>window.novex.appearance.setCape(id,capeId),'Cape applied to Minecraft.')}>Apply Selected Cape</button><button className="secondary-button" disabled={busy||!activeCape} onClick={()=>void run(id=>window.novex.appearance.disableCape(id),'Cape disabled. You still own it.')}>Disable Current Cape</button></section>
    {!data.capes.length&&<div className="card empty-state">This Minecraft account has no available capes. Novex cannot grant Mojang capes or upload custom capes.</div>}
    <div className="appearance-grid">{data.capes.map(cape=><button key={cape.id} className={`card appearance-pick ${capeId===cape.id?'selected':''}`} disabled={busy} aria-pressed={capeId===cape.id} onClick={()=>{setCapeId(cape.id);setMessage('');}}><AppearancePreview image={cape.url} cape label={`${cape.name} cape preview`}/><strong>{cape.name}</strong><span className="provider-badge">{cape.active?'Active':'Inactive'}{capeId===cape.id?' · Selected':''}</span></button>)}</div></>}
    </section>;
}
