import {useActivity} from '../services/activity';
import {useEffect,useState} from 'react';
import UpdateNotice from '../components/UpdateNotice';
import HomeCarousel from '../components/HomeCarousel';
import type {MinecraftInstance} from '../services/instances';
type Props={instances:MinecraftInstance[];username?:string;onPlay:(instance:MinecraftInstance)=>void;onOpenInstances:()=>void;onOpenMods:()=>void;onOpenFriends:()=>void;onOpenInstance:(instance:MinecraftInstance)=>void};
export default function Home({instances,username,onPlay,onOpenInstances,onOpenMods,onOpenFriends,onOpenInstance}:Props) {
    const jobs=useActivity();const busy=jobs.some(j=>['running','queued'].includes(j.status));
    const [name,setName]=useState(username||'player'),[modCount,setModCount]=useState<number|null>(null);
    const recent=[...instances].sort((a,b)=>(b.lastPlayedAt||b.createdAt)-(a.lastPlayedAt||a.createdAt));
    const featured=recent[0];
    useEffect(()=>{const reload=()=>{void window.novex.minecraftAccounts.list().then(s=>setName(s.accounts.find(a=>a.id===s.selectedId)?.username||username||'player')).catch(()=>{});};reload();window.addEventListener('novex-minecraft-accounts',reload);return()=>window.removeEventListener('novex-minecraft-accounts',reload);},[username]);
    useEffect(()=>{setModCount(null);if(featured)void window.novex.mods.list(featured).then(mods=>setModCount(mods.filter(m=>m.enabled).length)).catch(()=>{});},[featured?.id]);
    return <div className="home"><header><div className="eyebrow">YOUR MINECRAFT</div><h1>Welcome back, {name}</h1></header>
    {featured?<section className="quick-play card"><div className="quick-icon">{featured.icon?<img src={featured.icon} alt=""/>:<span>MC</span>}</div><div className="quick-copy"><span className="eyebrow">JUMP BACK IN</span><h2>{featured.name}</h2><p>Minecraft {featured.minecraftVersion} · {featured.loader}{modCount!==null?` · ${modCount} mods`:''}</p><small>{featured.lastPlayedAt?`Last played ${new Date(featured.lastPlayedAt).toLocaleString()}`:featured.status==='installing'?'Installing in the background':featured.status==='repair'?'Repair needed before playing':'Ready for your next adventure'}</small></div><div className="quick-actions"><button className="primary-button" disabled={busy || ['installing','repair'].includes(featured.status||'')} onClick={()=>onPlay(featured)}>▶ Play</button><button onClick={()=>onOpenInstance(featured)}>Overview</button></div></section>:<section className="card empty-state"><h2>Your next adventure starts here</h2><p>Create an instance to keep your Minecraft worlds and mods together.</p><button className="primary-button" onClick={onOpenInstances}>Create Instance</button></section>}
    <UpdateNotice/><section><div className="section-title"><h2>Recent instances</h2><button className="text-button" onClick={onOpenInstances}>View all →</button></div><div className="home-instance-grid">{recent.slice(0,3).map(instance=><article className="home-instance-card" key={instance.id}><div className="home-instance-info"><button className="text-button" onClick={()=>onOpenInstance(instance)}>{instance.name}</button><p>{instance.loader} · {instance.minecraftVersion}</p><small>{instance.status==='installing'?'Installing':instance.status==='repair'?'Needs Repair':'Ready'}</small></div><button className="primary-button" disabled={busy || ['installing','repair'].includes(instance.status||'')} onClick={()=>onPlay(instance)}>Play</button></article>)}</div></section>
    <section className="home-featured"><div className="section-title"><h2>Novex / News / Featured</h2></div><HomeCarousel><section className="home-hero"><div className="home-hero-copy"><div className="eyebrow">NOVEX CLIENT</div><h2>Your Minecraft. Your way.</h2><p>Explore mods, build your library and stay connected with friends.</p><div className="home-hero-actions"><button onClick={onOpenMods}>Browse Mods</button><button onClick={onOpenFriends}>Friends</button></div></div></section></HomeCarousel></section></div>;
}
