import { useEffect,useState,useRef } from 'react';
import type { MinecraftAccountsState } from '../services/minecraftAccounts';
export default function AccountSwitcher({onManage}:{onManage:()=>void}) {
    const [state,setState]=useState<MinecraftAccountsState|null>(null),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
    const root=useRef<HTMLDivElement>(null);
    useEffect(()=>{const reload=()=>{void window.novex.minecraftAccounts.list().then(setState).catch(()=>{});};reload();window.addEventListener('novex-minecraft-accounts',reload);return()=>window.removeEventListener('novex-minecraft-accounts',reload);},[]);
    useEffect(()=>{if(!open)return;const click=(e:PointerEvent)=>{if(!root.current?.contains(e.target as Node))setOpen(false);};const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false);};document.addEventListener('pointerdown',click);document.addEventListener('keydown',key);return()=>{document.removeEventListener('pointerdown',click);document.removeEventListener('keydown',key);};},[open]);
    async function perform(action:()=>Promise<MinecraftAccountsState>) {setBusy(true);setError('');try{setState(await action());window.dispatchEvent(new Event('novex-minecraft-accounts'));}catch(e){setError(e instanceof Error?e.message:'Account operation failed.');}finally{setBusy(false);}}
    const selected=state?.accounts.find(a=>a.id===state.selectedId);
    return <div className="account-switcher" ref={root}><button className="account-card" aria-expanded={open} onClick={()=>setOpen(!open)}><span className="minecraft-head" style={selected?.skinUrl?{backgroundImage:`url("${selected.skinUrl}")`}:{}}/>
    <span className="account-details"><strong>{selected?.username||'Minecraft accounts'}</strong><small>{selected?.type==='local'?'Offline / Local Account':selected?'Microsoft':'Add an account'}</small></span><span>⌃</span></button>
    {open&&<section className="account-popover" aria-label="Minecraft accounts"><h3>Minecraft Accounts</h3>{state?.accounts.map(a=><button key={a.id} className={`account-choice ${a.id===state.selectedId?'selected':''}`} disabled={busy} onClick={()=>void perform(()=>window.novex.minecraftAccounts.select(a.id))}><span className="minecraft-head" style={a.skinUrl?{backgroundImage:`url("${a.skinUrl}")`}:{}}/><span>{a.username}<small>{a.id===state.selectedId?'Selected':a.type==='local'?'Offline / Local Account':'Microsoft'}</small></span></button>)}<button disabled={busy} onClick={()=>void perform(()=>window.novex.minecraftAccounts.login())}>{busy?'Signing in…':'+ Add Microsoft Account'}</button>{busy&&<button onClick={()=>void window.novex.minecraftAccounts.cancel()}>Cancel sign-in</button>}<button onClick={()=>{setOpen(false);onManage();}}>Manage Accounts</button>{error&&<p className="error" role="alert">{error}</p>}</section>}</div>;
}
