import {useEffect,useState} from 'react';
import type {MinecraftInstance} from '../services/instances';
import {startInstallation,showActivity,useActivity} from '../services/activity';
import CompanionCard from './CompanionCard';
export default function InstanceOverview({instance,onPlay}:{instance:MinecraftInstance;onPlay:()=>void}) {
    const [data,setData]=useState<Awaited<ReturnType<typeof window.novex.overview>>|null>(null),[error,setError]=useState('');
    const jobs=useActivity(),active=jobs.some(j=>j.instanceId===instance.id&&['running','queued'].includes(j.status));
    const refresh=()=>window.novex.overview(instance).then(setData).catch(e=>setError(e.message));
    useEffect(()=>{void refresh();},[instance.id,active]);
    async function action(fn:()=>Promise<unknown>){try{setError('');await fn();await refresh();}catch(e){setError(e instanceof Error?e.message:'Operation failed.');}}
    return <div className="overview-grid"><section className="card"><div className="panel-heading"><h2>Overview</h2><span className="provider-badge">{active?'Installing':data?.state.status==='ready'?'Ready':'Needs Repair'}</span></div><dl className="overview-details"><dt>Minecraft</dt><dd>{instance.minecraftVersion} · {instance.loader}</dd><dt>Mods</dt><dd>{data?.mods??'…'} enabled</dd><dt>Last played</dt><dd>{instance.lastPlayedAt?new Date(instance.lastPlayedAt).toLocaleString():'Not played yet'}</dd><dt>Java</dt><dd>{data?.java?`Java ${data.java.major} · ${data.java.source}`:data?.error||'Checking…'}</dd></dl><div className="account-actions"><button className="primary-button" disabled={active||!data||data.state.status!=='ready'} onClick={onPlay}>Play</button><button disabled={active} onClick={()=>void action(()=>startInstallation(instance))}>Repair / Resume</button><button onClick={()=>void window.novex.instances.openFolder(instance)}>Open Folder</button></div></section>
    <section className="card"><h3>Java for this instance</h3><p>{data?.customJava||'Automatic (Recommended)'}</p><p>Required: {data?.required?`Java ${data.required} · 64-bit`:'Available after Minecraft metadata is loaded'}</p><div className="account-actions"><button disabled={active} onClick={()=>void action(()=>window.novex.java.choose(instance,false))}>Choose Java</button><button disabled={active} onClick={()=>void action(()=>window.novex.java.choose(instance,true))}>Automatic</button>{data?.required&&<button disabled={active} onClick={()=>void action(async()=>{await window.novex.java.install(data.required!);showActivity();})}>Install Java {data.required}</button>}</div></section><CompanionCard instance={instance}/>{(error||data?.state.error)&&<div className="card error"><p>{error||data?.state.error}</p><button onClick={()=>void window.novex.openLogs()}>Open Log</button></div>}</div>;
}
