import {useEffect,useState} from 'react';
import NovexSelect from './NovexSelect';
import {showActivity,useActivity} from '../services/activity';
import type {LauncherSettings} from '../services/minecraftAccounts';
export default function JavaSettings() {
    const [runtimes,setRuntimes]=useState<{path:string;major:number;source:string}[]>([]),[settings,setSettings]=useState<LauncherSettings|null>(null),[major,setMajor]=useState('21'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
    const jobs=useActivity(),active=jobs.some(j=>j.kind==='java'&&['running','queued'].includes(j.status));
    async function scan(){setBusy(true);try{setRuntimes(await window.novex.java.list());setSettings(await window.novex.settings.get());}catch(e){setError(e instanceof Error?e.message:'Unable to detect Java.');}finally{setBusy(false);}}
    useEffect(()=>{void scan();},[active]);
    async function change(input:Pick<LauncherSettings,'automaticJava'|'launchBehavior'>){try{setSettings(await window.novex.settings.setLaunch(input));}catch(e){setError(e instanceof Error?e.message:'Unable to save settings.');}}
    return <section className="card java-settings"><h2>Java & launch behavior</h2><p>Automatic selection uses each Minecraft version’s official Java requirement. Managed runtimes stay in Novex data; system Java is unchanged.</p><label className="settings-row"><span>Automatic Java management</span><input type="checkbox" checked={settings?.automaticJava??true} disabled={!settings} onChange={e=>settings&&void change({automaticJava:e.target.checked,launchBehavior:settings.launchBehavior})}/></label><div className="settings-field"><span>When Minecraft launches</span><NovexSelect label="When Minecraft launches" value={settings?.launchBehavior||'keep'} options={[{value:'keep',label:'Keep Novex open'},{value:'minimize',label:'Minimize Novex'},{value:'hide',label:'Hide Novex'}]} onChange={value=>settings&&void change({automaticJava:settings.automaticJava,launchBehavior:value as LauncherSettings['launchBehavior']})}/></div><h3>Detected runtimes</h3>{runtimes.map(java=><div className="runtime-row" key={java.path}><strong>Java {java.major}</strong><span>{java.source}</span><code>{java.path}</code></div>)}{!busy&&!runtimes.length&&<p>No compatible 64-bit runtime found.</p>}<div className="account-actions"><button disabled={busy} onClick={()=>void scan()}>{busy?'Scanning…':'Scan Again'}</button><NovexSelect label="Runtime to download" value={major} onChange={setMajor} options={['8','17','21','25'].map(value=>({value,label:`Java ${value}`}))}/><button disabled={active} onClick={async()=>{try{await window.novex.java.install(Number(major));showActivity();}catch(e){setError(e instanceof Error?e.message:'Unable to start download.');}}}>Download Runtime</button></div>{error&&<p className="error">{error}</p>}</section>;
}
